version: '3'

tasks:
  build:
    cmds:
      - go build
      - mkdir -p ~/.terraform.d/plugins/github.com/zolamk/webdock/0.1.0/linux_amd64/ && cp terraform-provider-webdock ~/.terraform.d/plugins/github.com/zolamk/webdock/0.1.0/linux_amd64/