// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	sdk "github.com/webdock-io/go-sdk"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

// CreatePublicKey provides a mock function with given fields: opts
func (_m *ClientInterface) CreatePublicKey(opts sdk.CreatePublicKeyOptions) (sdk.PublicKey, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for CreatePublicKey")
	}

	var r0 sdk.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.CreatePublicKeyOptions) (sdk.PublicKey, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(sdk.CreatePublicKeyOptions) sdk.PublicKey); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(sdk.PublicKey)
	}

	if rf, ok := ret.Get(1).(func(sdk.CreatePublicKeyOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateServerFromImage provides a mock function with given fields: ops
func (_m *ClientInterface) CreateServerFromImage(ops sdk.CreateServerFromImageOptions) (sdk.CreatedServer, error) {
	ret := _m.Called(ops)

	if len(ret) == 0 {
		panic("no return value specified for CreateServerFromImage")
	}

	var r0 sdk.CreatedServer
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.CreateServerFromImageOptions) (sdk.CreatedServer, error)); ok {
		return rf(ops)
	}
	if rf, ok := ret.Get(0).(func(sdk.CreateServerFromImageOptions) sdk.CreatedServer); ok {
		r0 = rf(ops)
	} else {
		r0 = ret.Get(0).(sdk.CreatedServer)
	}

	if rf, ok := ret.Get(1).(func(sdk.CreateServerFromImageOptions) error); ok {
		r1 = rf(ops)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateServerShellUser provides a mock function with given fields: opts
func (_m *ClientInterface) CreateServerShellUser(opts sdk.CreateServerShellUserOptions) (sdk.CreatedShellUser, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateServerShellUser")
	}

	var r0 sdk.CreatedShellUser
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.CreateServerShellUserOptions) (sdk.CreatedShellUser, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(sdk.CreateServerShellUserOptions) sdk.CreatedShellUser); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(sdk.CreatedShellUser)
	}

	if rf, ok := ret.Get(1).(func(sdk.CreateServerShellUserOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePublicKey provides a mock function with given fields: options
func (_m *ClientInterface) DeletePublicKey(options sdk.DeletePublicOptions) error {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for DeletePublicKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(sdk.DeletePublicOptions) error); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteServerBySlug provides a mock function with given fields: options
func (_m *ClientInterface) DeleteServerBySlug(options sdk.DeleteServerBySlugOptions) error {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServerBySlug")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(sdk.DeleteServerBySlugOptions) error); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteShellUser provides a mock function with given fields: options
func (_m *ClientInterface) DeleteShellUser(options sdk.DeleteShellUserOptions) (sdk.DeleteShellUserResponse, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShellUser")
	}

	var r0 sdk.DeleteShellUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.DeleteShellUserOptions) (sdk.DeleteShellUserResponse, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.DeleteShellUserOptions) sdk.DeleteShellUserResponse); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(sdk.DeleteShellUserResponse)
	}

	if rf, ok := ret.Get(1).(func(sdk.DeleteShellUserOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DryRunResizeServer provides a mock function with given fields: options
func (_m *ClientInterface) DryRunResizeServer(options sdk.DryRunResizeServerOptions) (sdk.ResizeDryRunResponse, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for DryRunResizeServer")
	}

	var r0 sdk.ResizeDryRunResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.DryRunResizeServerOptions) (sdk.ResizeDryRunResponse, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.DryRunResizeServerOptions) sdk.ResizeDryRunResponse); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(sdk.ResizeDryRunResponse)
	}

	if rf, ok := ret.Get(1).(func(sdk.DryRunResizeServerOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServerBySlug provides a mock function with given fields: options
func (_m *ClientInterface) GetServerBySlug(options sdk.GetServerBySlugOptions) (sdk.Server, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for GetServerBySlug")
	}

	var r0 sdk.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.GetServerBySlugOptions) (sdk.Server, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.GetServerBySlugOptions) sdk.Server); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(sdk.Server)
	}

	if rf, ok := ret.Get(1).(func(sdk.GetServerBySlugOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAccountPublicKeys provides a mock function with given fields: options
func (_m *ClientInterface) ListAccountPublicKeys(options sdk.ListAccountPublicKeysOptions) ([]sdk.PublicKey, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ListAccountPublicKeys")
	}

	var r0 []sdk.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListAccountPublicKeysOptions) ([]sdk.PublicKey, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListAccountPublicKeysOptions) []sdk.PublicKey); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sdk.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(sdk.ListAccountPublicKeysOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEvents provides a mock function with given fields: options
func (_m *ClientInterface) ListEvents(options sdk.ListEventsOptions) (sdk.ListEventsResponse, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 sdk.ListEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListEventsOptions) (sdk.ListEventsResponse, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListEventsOptions) sdk.ListEventsResponse); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(sdk.ListEventsResponse)
	}

	if rf, ok := ret.Get(1).(func(sdk.ListEventsOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLocations provides a mock function with given fields: options
func (_m *ClientInterface) ListLocations(options sdk.ListLocationsOptions) ([]sdk.Location, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ListLocations")
	}

	var r0 []sdk.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListLocationsOptions) ([]sdk.Location, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListLocationsOptions) []sdk.Location); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sdk.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(sdk.ListLocationsOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOSImages provides a mock function with given fields: options
func (_m *ClientInterface) ListOSImages(options sdk.ListOSImagesOptions) ([]sdk.Image, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ListOSImages")
	}

	var r0 []sdk.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListOSImagesOptions) ([]sdk.Image, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListOSImagesOptions) []sdk.Image); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sdk.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(sdk.ListOSImagesOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPossibleProfilesInLocation provides a mock function with given fields: opts
func (_m *ClientInterface) ListPossibleProfilesInLocation(opts sdk.ListPossibleProfilesInLocationOptions) ([]sdk.Profile, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ListPossibleProfilesInLocation")
	}

	var r0 []sdk.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListPossibleProfilesInLocationOptions) ([]sdk.Profile, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListPossibleProfilesInLocationOptions) []sdk.Profile); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sdk.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(sdk.ListPossibleProfilesInLocationOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServer provides a mock function with given fields: options
func (_m *ClientInterface) ListServer(options sdk.ListServerOptions) (sdk.ListServers, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ListServer")
	}

	var r0 sdk.ListServers
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListServerOptions) (sdk.ListServers, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListServerOptions) sdk.ListServers); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sdk.ListServers)
		}
	}

	if rf, ok := ret.Get(1).(func(sdk.ListServerOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServerShellUser provides a mock function with given fields: options
func (_m *ClientInterface) ListServerShellUser(options sdk.ListServerShellUserOptions) ([]sdk.ShellUser, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ListServerShellUser")
	}

	var r0 []sdk.ShellUser
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ListServerShellUserOptions) ([]sdk.ShellUser, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ListServerShellUserOptions) []sdk.ShellUser); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sdk.ShellUser)
		}
	}

	if rf, ok := ret.Get(1).(func(sdk.ListServerShellUserOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReinstallServer provides a mock function with given fields: options
func (_m *ClientInterface) ReinstallServer(options sdk.ReinstallServerOptions) (string, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ReinstallServer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ReinstallServerOptions) (string, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ReinstallServerOptions) string); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(sdk.ReinstallServerOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResizeServer provides a mock function with given fields: options
func (_m *ClientInterface) ResizeServer(options sdk.ResizeServersOptions) (string, error) {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for ResizeServer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.ResizeServersOptions) (string, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(sdk.ResizeServersOptions) string); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(sdk.ResizeServersOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateServer provides a mock function with given fields: opts
func (_m *ClientInterface) UpdateServer(opts sdk.UpdateServerOptions) (sdk.Server, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServer")
	}

	var r0 sdk.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.UpdateServerOptions) (sdk.Server, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(sdk.UpdateServerOptions) sdk.Server); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(sdk.Server)
	}

	if rf, ok := ret.Get(1).(func(sdk.UpdateServerOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateServerShellUser provides a mock function with given fields: opts
func (_m *ClientInterface) UpdateServerShellUser(opts sdk.UpdateServerShellUserOptions) (sdk.ShellUser, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServerShellUser")
	}

	var r0 sdk.ShellUser
	var r1 error
	if rf, ok := ret.Get(0).(func(sdk.UpdateServerShellUserOptions) (sdk.ShellUser, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(sdk.UpdateServerShellUserOptions) sdk.ShellUser); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(sdk.ShellUser)
	}

	if rf, ok := ret.Get(1).(func(sdk.UpdateServerShellUserOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
